#!/bin/bash

docker run -d --name=jupyter --restart=always -v /data/jupyter/hksitorus:/home/hksitorus -v /data/jupyter/arifsolomon:/home/arifsolomon -v /data/jupyter/fchrulk:/home/fchrulk -v /data/jupyter/shared:/data/jupyter/shared -v /data/jupyter/shared:/shared -v /data/jupyter/jupyterhub:/home/jupyterhub -w /home/jupyterhub --net=host hksitorus/jupyter-kaggle:latest
