#!/bin/bash

docker run -d --restart=always -v /mnt/jupyter/hksitorus:/home/hksitorus -v /mnt/jupyter/arifsolomon:/home/arifsolomon -v /mnt/jupyter/fchrulk:/home/fchrulk -v /mnt/jupyter/shared:/shared -v /home/putin/jupyterhub:/home/jupyterhub -w /home/jupyterhub -p 127.0.0.1:8081:3030 jupyter-kaggle:latest
