#!/bin/bash

docker run -it --rm -v /data/jupyter/hksitorus:/home/hksitorus -v /data/jupyter/arifsolomon:/home/arifsolomon -v /data/jupyter/fchrulk:/home/fchrulk -v /data/jupyter/shared:/shared -v /data/jupyter/jupyterhub:/home/jupyterhub -w /home/jupyterhub -p 127.0.0.1:8081:3030 jupyter-kaggle:latest
